config/routes.rb
Rails.application.routes.draw do
  resources :statuses
  resources :clients
  resources :purchases
  resources :products
  devise_for :users

  get 'fetch_clients' => 'clients#fetch_clients'
  get 'fetch_products' => 'products#fetch_products'
  root to: 'home#index'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.slim
= form_for @status do |f|
  - if @status.errors.any?
    #error_explanation
      h2 = "#{pluralize(@status.errors.count, "error")} prohibited this status from being saved:"
      ul
        - @status.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit 'Salvar', class:'btn'

app/views/statuses/edit.html.slim
h1 
    = t(:edit) + ' ' + t(:status)

== render 'form'

= link_to t(:show), @status, class: 'btn'
br
= link_to t(:back), statuses_path, class: 'btn'

app/views/statuses/index.html.slim
h1 
  = t(:list_status)

table
  thead
    tr
      th Name
      th
      th 
      th

  tbody
    - @statuses.each do |status|
      tr
        td = status.name
        td = link_to t(:show), status, class: 'btn'
        td = link_to t(:edit), edit_status_path(status), class: 'btn'
        td = link_to t(:remove), status, data: { confirm: 'Confirma?' }, method: :delete, class: 'btn'

br

= link_to t(:new_status), new_status_path, class: 'btn'

app/views/statuses/new.html.slim
h1 Novo status

== render 'form'

= link_to t(:back), statuses_path, class: 'btn'

app/views/statuses/show.html.slim
p#notice = notice

p
  strong 
    = t(:name)
  = @status.name

= link_to t(:edit), edit_status_path(@status), class: 'btn'
br
= link_to t(:back), statuses_path, class: 'btn'