config/routes.rb
Rails.application.routes.draw do
  resources :statuses
  resources :clients
  resources :purchases
  resources :products
  devise_for :users

  get 'fetch_clients' => 'clients#fetch_clients'
  get 'fetch_products' => 'products#fetch_products'
  root to: 'home#index'

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  # GET /purchases
  # GET /purchases.json
  def index
    @search = PurchaseSearchService.new(params).search
    @purchases = @search.result.joins(:product).select('Purchases.*, (Purchases.qtd * Products.ValorUnitario) total')
    @purchases = @purchases.order(params.dig(:q,:s)) if params[:q].present?
    @purchases = @purchases.paginate(page: params[:page].nil? ? 1 : params[:page], per_page: params[:per_page].nil? ? 10 : params[:per_page])
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Pedido compra was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Pedido compra was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Pedido compra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params[:dtPedido] = params[:dtPedido_submit]
      puts params.inspect
      params.permit(:client_id,:status_id, :product_id, :qtd, :dtPedido)
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form.html.slim
= form_for @purchase, multipart: true  do |f|
  - if @purchase.errors.any?
    #error_explanation
      h2 = "#{pluralize(@purchase.errors.count, "error")} prohibited this purchase from being saved:"
      ul
        - @purchase.errors.full_messages.each do |message|
          li = message
  
  

= form_tag @purchase do |f|
  .field
    = label_tag 'Cliente'
    = select_tag :client_id,  t(:select_client_option),   class: "browser-default" , required: true

  .field
    = label_tag 'Produto'    
    = select_tag :product_id,  t(:select_product_option),   class: "browser-default" , required: true
  .field
    = label_tag t(:status)
    = select_tag :status_id ,options_from_collection_for_select(Status.all, :id, :name), class:'browser-default', required: true
  .field
    = label_tag 'Quantidade'
    = number_field_tag :qtd, required: true
  .field
    = label_tag 'Data do pedido'
    = text_field_tag :dtPedido, '', class: 'datepicker', onkeypress: 'function() {return false;}', required: true
  .actions 
    = submit_tag 'Salvar', class:'btn'


javascript:
      $(document).ready(function() {
        init_materialize_date_pt_br();

        $('#status_id').select2({
          placeholder: "Selecione...",
          width: "element"
        });
        $('#client_id').select2({
          placeholder: "#{t(:select_client_option)}",
          width: "element",
          ajax: {
            url: "#{fetch_clients_path}",
            dataType: "json",
            processResults: function(data) {
              return { results:data}
             }
            }
          }
        );

        $('#product_id').select2({
          placeholder: "#{t(:select_product_option)}",
          width: "element",
          ajax: {
            url: "#{fetch_products_path}",
            dataType: "json",
            processResults: function(data) {
              return { results:data}
             }
            }
          }
        );

      });

app/views/purchases/_search.html.slim
.card.l12
    .container        
            = search_form_for(@search, url: purchases_path, method: :get, html: { class: 'ransack-form' }) do |f|
                .row
                    .field.col.m4
                        = f.search_field  :NomeProduct_cont,  placeholder: t(:name), value: params.dig(:q, :NomeProduct_cont)
                    .field.col.m4
                        = f.search_field  :CodBarras_cont, placeholder: t('placeholder.q.CodBarras_cont'), value: params.dig(:q, :CodBarras_cont), type: 'number'
                    .field.col.m4
                        = f.search_field  :id_cont, placeholder: t('placeholder.q.id_cont'), value: params.dig(:q, :id_cont), type: 'number'
                .row
                    .field.col.m4
                        = f.select :client_id_eq,  t(:select_client_option),   class: "browser-default" , style: 'width:30%'
                    .field.col.m4
                        = f.select :product_id_eq,  t(:select_product_option),   class: "browser-default" , style: 'width:30%'
                    .field.col.m4
                        = f.select :status_id_eq ,options_from_collection_for_select( Status.all, :id, :name),:include_blank => 'Status', class:'browser-default', style: 'width:30%'
                    
                .row
                    .field.col.m5
                        = f.search_field  :qtd_gteq,  placeholder: t(:min_qtd), value: params.dig(:q, :qtd_gteq), type: 'number'
                    .field.col.m5
                        = f.search_field  :qtd_lteq, placeholder: t(:max_qtd), value: params.dig(:q, :qtd_lteq), type: 'number'
                    .field.col.m1
                        = render 'layouts/per_page_select'
                        = hidden_field_tag :page, '1', {class: 'ransack-page'}
                    
                    .field.col.m1 style='padding-top: 16px;'
                        span.icon-search 
                            = f.submit '', class: 'btn '

javascript:
      $(document).ready(function() {
        init_materialize_date_pt_br();

        $('#q_status_id_eq').select2({
          placeholder: "Selecione...",
          width: "100%"
        });
        $('#q_client_id_eq').select2({
          placeholder: "#{t(:select_client_option)}",
          width: "100%",
          ajax: {
            url: "#{fetch_clients_path}",
            dataType: "json",
            processResults: function(data) {
              return { results:data}
             }
            }
          }
        );

        $('#q_product_id_eq').select2({
          placeholder: "#{t(:select_product_option)}",
          width: "100%",
          ajax: {
            url: "#{fetch_products_path}",
            dataType: "json",
            processResults: function(data) {
              return { results:data}
             }
            }
          }
        );

      });

app/views/purchases/edit.html.slim
h1 Editing purchase

== render 'form'

= link_to t(:show), @purchase, class: 'btn'
br
= link_to t(:back), purchases_path, class: 'btn'

app/views/purchases/index.html.slim
h1 
  = t(:list_purchase)
  br
= render 'purchases/search'
br
= link_to t(:new_purchase), new_purchase_path, class:'l12 btn'
br
.row.center.col.l12
  br
  = will_paginate @purchases, previous_label: t(:previous), next_label: t(:next), inner_window: 1, outer_window: 1, class: 'l12 pagination'

.row.l12
  table.bordered.striped.centered.responsive-table
    thead
      tr
        th 
          = sort_link @search, :id, '#'
        th 
          = sort_link @search, :status_name, t(:status)
        th 
          = sort_link @search, :dtPedido, t(:date)
        th 
          = sort_link @search, :qtd, 'Qtd.'
        th 
          = sort_link @search, :total, 'Total'
        th 
        th 
        th
        th Ações
        th

    tbody
      - @purchases.each do |purchase|
        tr
          td = purchase.id
          td = purchase.status.name
          td = purchase.dtPedido.strftime("%d/%m/%Y")
          td = purchase.qtd
          td 
            = purchase.total_value
          td 
            = purchase.client.Nome
            br
              span.icon.icon-show
                = link_to('', client_path(purchase.client), class: 'btn') if purchase.client.present?
          td 
            = purchase.product.NomeProduct
            br
              span.icon.icon-show
                = link_to('', product_path(purchase.product), class: 'btn') if purchase.product.present?
          td 
            span.icon.icon-show
              = link_to('', purchase, class: 'btn')            
          td  
            span.icon.icon-edit
              = link_to '', edit_purchase_path(purchase), class: 'btn'
          td  
            span.icon.icon-delete
              = link_to '', purchase, data: { confirm: t(:are_you_sure) }, method: :delete, class: 'btn'

  br

app/views/purchases/new.html.slim
h1 
    = t(:new_purchase)

== render 'form'

= link_to t(:back), purchases_path, class: 'btn'

app/views/purchases/show.html.slim
p#notice = notice
.card
  p
    strong 
      = t(:client) + ': '
    = @purchase.client.Nome
  p
    strong 
      = t(:product) + ': '
    = @purchase.product.NomeProduct
  p
    strong 
      = t(:status) + ': '
    = @purchase.status.name
  p
    strong
      = t(:qtd) + ': '
    = @purchase.qtd
  p
    strong Total:
    = @purchase.qtd * @purchase.product.ValorUnitario
  p
    strong 
      = t(:purchase_date) + ': '
    = @purchase.dtPedido.strftime("%d/%m/%Y")
  p
    = link_to t(:edit), edit_purchase_path(@purchase), class: 'btn'
  p
    = link_to t(:back), purchases_path, class: 'btn'
  br