config/routes.rb
Rails.application.routes.draw do
  resources :statuses
  resources :clients
  resources :purchases
  resources :products
  devise_for :users

  get 'fetch_clients' => 'clients#fetch_clients'
  get 'fetch_products' => 'products#fetch_products'
  root to: 'home#index'

end

app/views/layouts/_navbar.html.slim
nav
  .nav-wrapper
    a.brand-logo.center href="#"
      | TESTE WKM
    a.button-collapse.right.btn data-activates="slide-out" href="#"  style="display:block"
      | menu

app/views/layouts/_per_page_select.html.slim
= select_tag :per_page, options_for_select([ 10, 20, 50, 100 ], params.dig(:per_page)), class: 'page_select'

javascript:
    $(document).ready(function() {
        $('.page_select').material_select();
    })

app/views/layouts/_sidenav.html.slim
ul#slide-out.side-nav
  li
    = link_to t(:home), root_path, class: 'btn'
  li
    = link_to t(:list_product), products_path, class: 'btn'
  li
    = link_to t(:list_purchase), purchases_path, class: 'btn'
  li
    = link_to t(:list_client), clients_path, class: 'btn'
  li
    = link_to t(:list_status), statuses_path, class: 'btn'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TESTWKM</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"   rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  
  
  <%= csrf_meta_tags %>
</head>
<body class='center'>
  <%= render 'layouts/sidenav'%>
  <%= render 'layouts/navbar'%>
  <div id='main' class='container'>
    <%= yield %>
  </div>

  <script>

  $('.button-collapse').sideNav({
        menuWidth: '80%', // Default is 240
        closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
      }
    );
    $('.collapsible').collapsible();
  </script>

</body>
</html>